# Generated by Django 4.2 on 2026-02-23 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outputs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationrun',
            name='json_key',
            field=models.TextField(blank=True, help_text='R2 path to GSTR1 JSON file'),
        ),
    ]
